from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """shared memory passed between all nodes in the graph.
    each node reads what it needs, updates its fields, and passes it forward.
    this is the only way nodes communicate with each other."""

    messages:            List[dict]           # conversation history (user + assistant messages)
    current_query:       str                  # the search query sent to ChromaDB (may be rephrased)
    retrieved_chunks:    List[dict]           # book chunks returned from ChromaDB after filtering
    retrieval_attempts:  int                  # how many times we've searched ChromaDB (max 3)
    is_enough:           bool                 # did the evaluator approve the retrieved chunks?
    retry_reason:        Optional[str]        # why the evaluator rejected the chunks
    active_frameworks:   List[str]            # which books were actually cited in the response
    action_plan:         Optional[List[str]]  # concrete steps generated by action_planner
    final_response:      Optional[str]        # the psychologist node's advice to the user
    should_loop:         bool                 # whether to continue the conversation loop
    turn_count:          int                  # number of completed conversation turns
    is_off_topic:        bool                 # did the guard reject this message?
    follow_up_question:  Optional[str]        # follow-up question generated by follow_up node
