from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """
    Shared state dictionary carried through the entire agent graph.

    Attributes:
        messages: Conversation history containing user and assistant messages.
        current_query: The search query sent to ChromaDB, may be rephrased on retries.
        retrieved_chunks: Book chunks returned from ChromaDB after filtering.
        retrieval_attempts: How many times ChromaDB has been searched (max 3).
        is_enough: Whether the evaluator approved the retrieved chunks.
        retry_reason: Explanation of why the evaluator rejected the chunks.
        active_frameworks: Which books were actually cited in the response.
        action_plan: Concrete steps generated by the action_planner node.
        final_response: The psychologist node's advice to the user.
        should_loop: Whether to continue the conversation loop.
        turn_count: Number of completed conversation turns.
        is_off_topic: Whether the guard rejected this message as off-topic.
        follow_up_question: Follow-up question generated by the follow_up node.
    """

    messages:            List[dict]
    current_query:       str
    retrieved_chunks:    List[dict]
    retrieval_attempts:  int
    is_enough:           bool
    retry_reason:        Optional[str]
    active_frameworks:   List[str]
    action_plan:         Optional[List[str]]
    final_response:      Optional[str]
    should_loop:         bool
    turn_count:          int
    is_off_topic:        bool
    follow_up_question:  Optional[str]
